---
apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-c6cwj
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:55Z"
  name: default
  namespace: openshift
  resourceVersion: "902"
  selfLink: /api/v1/namespaces/openshift/serviceaccounts/default
  uid: fdafbd25-bfe8-11ec-b9cc-42010a000003
secrets:
- name: default-token-595nb
- name: default-dockercfg-c6cwj
