---
apiVersion: v1
data:
  controller-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
    leaderElection:
      namespace: openshift-console-operator
    servingInfo:
      bindNetwork: "tcp"
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"controller-config.yaml":"apiVersion: operator.openshift.io/v1alpha1\nkind: GenericOperatorConfig\nleaderElection:\n  namespace: openshift-console-operator\nservingInfo:\n  bindNetwork: \"tcp\"\n"},"kind":"ConfigMap","metadata":{"annotations":{"include.release.openshift.io/ibm-cloud-managed":"true","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true"},"name":"console-operator-config","namespace":"openshift-console-operator"}}
  creationTimestamp: "2022-04-21T08:48:48Z"
  name: console-operator-config
  namespace: openshift-console-operator
  resourceVersion: "352246"
  selfLink: /api/v1/namespaces/openshift-console-operator/configmaps/console-operator-config
  uid: dc2e233d-c14f-11ec-b9cc-42010a000003
