---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.openshift.io/inject-proxy: console-operator
    deployment.kubernetes.io/revision: "4"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"config.openshift.io/inject-proxy":"console-operator","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true"},"name":"console-operator","namespace":"openshift-console-operator"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"console-operator"}},"template":{"metadata":{"annotations":{"target.workload.openshift.io/management":"{\"effect\": \"PreferredDuringScheduling\"}"},"labels":{"name":"console-operator"}},"spec":{"containers":[{"args":["-v=2","--config=/var/run/configmaps/config/controller-config.yaml"],"command":["console","operator"],"env":[{"name":"CONSOLE_IMAGE","value":"registry.svc.ci.openshift.org/openshift:console"},{"name":"DOWNLOADS_IMAGE","value":"registry.svc.ci.openshift.org/openshift:cli-artifacts"},{"name":"RELEASE_VERSION","value":"0.0.1-snapshot"},{"name":"OPERATOR_NAME","value":"console-operator"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}],"image":"registry.svc.ci.openshift.org/openshift:console-operator","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthz","port":8443,"scheme":"HTTPS"}},"name":"console-operator","ports":[{"containerPort":60000,"name":"metrics"}],"readinessProbe":{"httpGet":{"path":"/readyz","port":8443,"scheme":"HTTPS"}},"resources":{"requests":{"cpu":"10m","memory":"100Mi"}},"terminationMessagePolicy":"FallbackToLogsOnError","volumeMounts":[{"mountPath":"/var/run/configmaps/config","name":"config"},{"mountPath":"/var/run/secrets/serving-cert","name":"serving-cert"}]}],"nodeSelector":{"node-role.kubernetes.io/master":""},"priorityClassName":"system-cluster-critical","serviceAccountName":"console-operator","tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","operator":"Exists"},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":120},{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":120}],"volumes":[{"configMap":{"name":"console-operator-config"},"name":"config"},{"name":"serving-cert","secret":{"optional":true,"secretName":"serving-cert"}}]}}}}
  creationTimestamp: "2022-04-21T08:48:48Z"
  generation: 4
  name: console-operator
  namespace: openshift-console-operator
  resourceVersion: "353726"
  selfLink: /apis/apps/v1/namespaces/openshift-console-operator/deployments/console-operator
  uid: dc3ea655-c14f-11ec-b9cc-42010a000003
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: console-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      creationTimestamp: null
      labels:
        name: console-operator
    spec:
      containers:
      - args:
        - -v=2
        - --config=/var/run/configmaps/config/controller-config.yaml
        command:
        - console
        - operator
        env:
        - name: CONSOLE_IMAGE
          value: registry.svc.ci.openshift.org/openshift:console
        - name: DOWNLOADS_IMAGE
          value: registry.svc.ci.openshift.org/openshift:cli-artifacts
        - name: RELEASE_VERSION
          value: 0.0.1-snapshot
        - name: OPERATOR_NAME
          value: console-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.svc.ci.openshift.org/openshift:console-operator
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: console-operator
        ports:
        - containerPort: 60000
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: console-operator
      serviceAccountName: console-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 120
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: console-operator-config
        name: config
      - name: serving-cert
        secret:
          defaultMode: 420
          optional: true
          secretName: serving-cert
status: {}
---
apiVersion: v1
imagePullSecrets:
- name: console-operator-dockercfg-cf5q7
kind: ServiceAccount
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"include.release.openshift.io/ibm-cloud-managed":"true","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true"},"name":"console-operator","namespace":"openshift-console-operator"}}
  creationTimestamp: "2022-04-21T08:48:48Z"
  name: console-operator
  namespace: openshift-console-operator
  resourceVersion: "352262"
  selfLink: /api/v1/namespaces/openshift-console-operator/serviceaccounts/console-operator
  uid: dc34301f-c14f-11ec-b9cc-42010a000003
secrets:
- name: console-operator-token-nmjls
- name: console-operator-dockercfg-cf5q7
