---
apiVersion: v1
imagePullSecrets:
- name: deployer-dockercfg-lcxjg
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-21T08:48:47Z"
  name: deployer
  namespace: openshift-console-operator
  resourceVersion: "352226"
  selfLink: /api/v1/namespaces/openshift-console-operator/serviceaccounts/deployer
  uid: dbb67fe9-c14f-11ec-b9cc-42010a000003
secrets:
- name: deployer-token-r27wh
- name: deployer-dockercfg-lcxjg
