version: "3"
services:
  shifter-ui:
    container_name: shifter_ui_development
    domainname: shifter.local
    image: local.images.shifter.cloud/shifter-ui:latest
    environment:
      SHIFTER_SERVER_ENDPOINT: "http://shifter-server:7762/api/v1"
    ports:
      - 7761:8080
    links:
      - "shifter-server:shifter-server.local"
    networks:
      - shifter-network
  shifter-server:
    container_name: shifter_server_development
    domainname: shifter-server.local
    image: local.images.shifter.cloud/shifter:latest
    entrypoint: ["./shifter", "server"]
    ports:
      - 7762:8080
    networks:
      - shifter-network
  reverseproxy:
    container_name: shifter_nginx
    image: nginx:latest
    ports:
      - 9090:8080
      - 9091:8081
    volumes:
      - ./localhost.nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - shifter-network
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - shifter-server
      - shifter-ui
networks:
  shifter-network:
    external: true
