---
apiVersion: v1
data:
  webconsole-config.yaml: |
    apiVersion: webconsole.config.openshift.io/v1
    clusterInfo:
      adminConsolePublicURL: https://console.okd.shifter.cloud:8443/
      consolePublicURL: https://console.okd.shifter.cloud:8443/console/
      loggingPublicURL: https://kibana.okd.shifter.cloud
      logoutPublicURL: ''
      masterPublicURL: https://console.okd.shifter.cloud:8443
      metricsPublicURL: https://hawkular-metrics.okd.shifter.cloud/hawkular/metrics
    extensions:
      properties: {}
      scriptURLs: []
      stylesheetURLs: []
    features:
      clusterResourceOverridesEnabled: false
      inactivityTimeoutMinutes: 0
    kind: WebConsoleConfiguration
    servingInfo:
      bindAddress: 0.0.0.0:8443
      bindNetwork: tcp4
      certFile: /var/serving-cert/tls.crt
      clientCA: ''
      keyFile: /var/serving-cert/tls.key
      maxRequestsInFlight: 0
      namedCertificates: null
      requestTimeoutSeconds: 0
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-19T14:04:29Z"
  name: webconsole-config
  namespace: openshift-web-console
  resourceVersion: "14818"
  selfLink: /api/v1/namespaces/openshift-web-console/configmaps/webconsole-config
  uid: a178b9bf-bfe9-11ec-b9cc-42010a000003
