---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
    service.alpha.openshift.io/serving-cert-secret-name: controllermanager-ssl
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1650376713
  creationTimestamp: "2022-04-19T14:10:36Z"
  name: controller-manager
  namespace: kube-service-catalog
  resourceVersion: "4073"
  selfLink: /api/v1/namespaces/kube-service-catalog/services/controller-manager
  uid: 7c0337b6-bfea-11ec-b9cc-42010a000003
spec:
  clusterIP: 172.30.210.98
  ports:
  - name: secure
    port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    app: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
