---
apiVersion: v1
imagePullSecrets:
- name: deployer-dockercfg-8pjqn
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-06-02T22:59:29Z"
  name: deployer
  namespace: demo-100
  resourceVersion: "8723304"
  selfLink: /api/v1/namespaces/demo-100/serviceaccounts/deployer
  uid: a8a10170-e2c7-11ec-b9cc-42010a000003
secrets:
- name: deployer-dockercfg-8pjqn
- name: deployer-token-pbv49
