---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
  creationTimestamp: "2022-04-19T15:34:29Z"
  labels:
    template: mysql-persistent-template
    template.openshift.io/template-instance-owner: 33ee1d43-bff6-11ec-b9cc-42010a000003
  name: mysql
  namespace: get-off-open-shift
  resourceVersion: "15854"
  selfLink: /api/v1/namespaces/get-off-open-shift/services/mysql
  uid: 33f445a0-bff6-11ec-b9cc-42010a000003
spec:
  clusterIP: 172.30.158.155
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  creationTimestamp: "2022-04-19T15:34:29Z"
  generation: 2
  labels:
    template: mysql-persistent-template
    template.openshift.io/template-instance-owner: 33ee1d43-bff6-11ec-b9cc-42010a000003
  name: mysql
  namespace: get-off-open-shift
  resourceVersion: "16020"
  selfLink: /apis/apps.openshift.io/v1/namespaces/get-off-open-shift/deploymentconfigs/mysql
  uid: 33f7026d-bff6-11ec-b9cc-42010a000003
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: mysql
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql
        image: docker-registry.default.svc:5000/openshift/mysql@sha256:e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
              -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql
status: {}
