---
apiVersion: v1
imagePullSecrets:
- name: builder-dockercfg-r65zh
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:55Z"
  name: builder
  namespace: kube-system
  resourceVersion: "909"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/builder
  uid: fdcdff96-bfe8-11ec-b9cc-42010a000003
secrets:
- name: builder-token-k4424
- name: builder-dockercfg-r65zh
