---
apiVersion: v1
imagePullSecrets:
- name: expand-controller-dockercfg-7vrwb
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:54Z"
  name: expand-controller
  namespace: kube-system
  resourceVersion: "816"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/expand-controller
  uid: fd7b36b1-bfe8-11ec-b9cc-42010a000003
secrets:
- name: expand-controller-token-q9p82
- name: expand-controller-dockercfg-7vrwb
