---
apiVersion: v1
imagePullSecrets:
- name: horizontal-pod-autoscaler-dockercfg-dnksv
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:54Z"
  name: horizontal-pod-autoscaler
  namespace: kube-system
  resourceVersion: "810"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/horizontal-pod-autoscaler
  uid: fd3f2749-bfe8-11ec-b9cc-42010a000003
secrets:
- name: horizontal-pod-autoscaler-token-djmj9
- name: horizontal-pod-autoscaler-dockercfg-dnksv
