---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"dev-cluster-cp-0_f12fede7-bfe8-11ec-9f45-42010a000003","leaseDurationSeconds":15,"acquireTime":"2022-04-19T13:59:51Z","renewTime":"2022-08-01T10:10:32Z","leaderTransitions":0}'
  creationTimestamp: "2022-04-19T13:59:51Z"
  name: kube-scheduler
  namespace: kube-system
  resourceVersion: "21099219"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-scheduler
  uid: fb451cf1-bfe8-11ec-b9cc-42010a000003
