---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-19T14:07:16Z"
  labels:
    k8s-app: kubelet
  name: kubelet
  namespace: kube-system
  resourceVersion: "3298"
  selfLink: /api/v1/namespaces/kube-system/services/kubelet
  uid: 04f6da3f-bfea-11ec-b9cc-42010a000003
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
    targetPort: 10250
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
