---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-19T14:04:52Z"
  labels:
    k8s-app: kube-controllers
  name: kube-controllers
  namespace: kube-system
  resourceVersion: "2484"
  selfLink: /api/v1/namespaces/kube-system/services/kube-controllers
  uid: af128702-bfe9-11ec-b9cc-42010a000003
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8444
    protocol: TCP
    targetPort: 8444
  selector:
    openshift.io/component: controllers
    openshift.io/control-plane: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
