---
apiVersion: v1
imagePullSecrets:
- name: node-controller-dockercfg-kxs8h
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:54Z"
  name: node-controller
  namespace: kube-system
  resourceVersion: "828"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/node-controller
  uid: fd761f25-bfe8-11ec-b9cc-42010a000003
secrets:
- name: node-controller-token-pqzxw
- name: node-controller-dockercfg-kxs8h
