---
apiVersion: v1
imagePullSecrets:
- name: replication-controller-dockercfg-bxm7p
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:54Z"
  name: replication-controller
  namespace: kube-system
  resourceVersion: "835"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/replication-controller
  uid: fd3702d1-bfe8-11ec-b9cc-42010a000003
secrets:
- name: replication-controller-token-2hf4k
- name: replication-controller-dockercfg-bxm7p
