---
apiVersion: v1
imagePullSecrets:
- name: service-controller-dockercfg-6djbd
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:54Z"
  name: service-controller
  namespace: kube-system
  resourceVersion: "842"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/service-controller
  uid: fd56076d-bfe8-11ec-b9cc-42010a000003
secrets:
- name: service-controller-token-qrk6z
- name: service-controller-dockercfg-6djbd
