---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-06-10T14:42:49Z"
  labels:
    app: django-psql-persistent
    template: django-psql-persistent
    template.openshift.io/template-instance-owner: 9968fdc7-e8cb-11ec-b9cc-42010a000003
  name: django-psql-persistent-gdc
  namespace: gdc-example
  resourceVersion: "10349898"
  selfLink: /apis/route.openshift.io/v1/namespaces/gdc-example/routes/django-psql-persistent-gdc
  uid: 996f5340-e8cb-11ec-b9cc-42010a000003
spec:
  rules:
  - host: django-psql-persistent-gdc-gdc-example.okd.shifter.cloud
    http:
      paths:
      - backend:
          service:
            name: django-psql-persistent-gdc
            port: {}
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"name": "postgresql", "kind": "Service"}]'
  creationTimestamp: "2022-06-10T14:42:49Z"
  labels:
    app: django-psql-persistent
    template: django-psql-persistent
    template.openshift.io/template-instance-owner: 9968fdc7-e8cb-11ec-b9cc-42010a000003
  name: django-psql-persistent-gdc
  namespace: gdc-example
  resourceVersion: "10349893"
  selfLink: /api/v1/namespaces/gdc-example/services/django-psql-persistent-gdc
  uid: 996ecd41-e8cb-11ec-b9cc-42010a000003
spec:
  clusterIP: 172.30.61.89
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: django-psql-persistent-gdc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: "true"
  creationTimestamp: "2022-06-10T14:42:49Z"
  generation: 1
  labels:
    app: django-psql-persistent
    template: django-psql-persistent
    template.openshift.io/template-instance-owner: 9968fdc7-e8cb-11ec-b9cc-42010a000003
  name: django-psql-persistent-gdc
  namespace: gdc-example
  resourceVersion: "10349901"
  selfLink: /apis/apps.openshift.io/v1/namespaces/gdc-example/deploymentconfigs/django-psql-persistent-gdc
  uid: 997348b8-e8cb-11ec-b9cc-42010a000003
spec:
  replicas: 1
  selector:
    matchLabels:
      name: django-psql-persistent-gdc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: django-psql-persistent-gdc
      name: django-psql-persistent-gdc
    spec:
      containers:
      - env:
        - name: DATABASE_SERVICE_NAME
          value: postgresql
        - name: DATABASE_ENGINE
          value: postgresql
        - name: DATABASE_NAME
          value: default
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: django-psql-persistent-gdc
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: django-psql-persistent-gdc
        - name: APP_CONFIG
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: django-psql-persistent-gdc
        image: ' '
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: django-psql-persistent
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
