---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"kubernetes.io/cluster-service":"true","kubernetes.io/name":"Metrics-server","metrics-server-infra":"metrics-server"},"name":"metrics-server","namespace":"openshift-metrics-server"},"spec":{"ports":[{"port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"k8s-app":"metrics-server"}}}
  creationTimestamp: "2022-04-19T14:07:31Z"
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Metrics-server
    metrics-server-infra: metrics-server
  name: metrics-server
  namespace: openshift-metrics-server
  resourceVersion: "3344"
  selfLink: /api/v1/namespaces/openshift-metrics-server/services/metrics-server
  uid: 0d82d609-bfea-11ec-b9cc-42010a000003
spec:
  clusterIP: 172.30.62.31
  ports:
  - port: 443
    protocol: TCP
    targetPort: https
  selector:
    k8s-app: metrics-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"metrics-server","kubernetes.io/cluster-service":"true","metrics-server-infra":"metrics-server"},"name":"metrics-server","namespace":"openshift-metrics-server"},"spec":{"selector":{"matchLabels":{"k8s-app":"metrics-server"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-app":"metrics-server"},"name":"metrics-server"},"spec":{"containers":[{"command":["/usr/bin/metrics-server","--source=kubernetes.summary_api:?useServiceAccount=true\u0026kubeletHttps=true\u0026kubeletPort=10250","--tls-cert-file=/certs/tls.crt","--tls-private-key-file=/certs/tls.key","--metric_resolution=30s","--secure-port=8443"],"image":"quay.io/openshift/origin-metrics-server:v3.11","name":"metrics-server","ports":[{"containerPort":8443,"name":"https","protocol":"TCP"}],"volumeMounts":[{"mountPath":"/certs","name":"metrics-server-certs","readOnly":true}]}],"nodeSelector":{"node-role.kubernetes.io/infra":"true"},"priorityClassName":"system-cluster-critical","serviceAccountName":"metrics-server","volumes":[{"name":"metrics-server-certs","secret":{"defaultMode":420,"secretName":"metrics-server-certs"}}]}}}}
  creationTimestamp: "2022-04-19T14:07:33Z"
  generation: 1
  labels:
    k8s-app: metrics-server
    kubernetes.io/cluster-service: "true"
    metrics-server-infra: metrics-server
  name: metrics-server
  namespace: openshift-metrics-server
  resourceVersion: "3406"
  selfLink: /apis/apps/v1/namespaces/openshift-metrics-server/deployments/metrics-server
  uid: 0eace8f3-bfea-11ec-b9cc-42010a000003
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: metrics-server
      name: metrics-server
    spec:
      containers:
      - command:
        - /usr/bin/metrics-server
        - --source=kubernetes.summary_api:?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
        - --tls-cert-file=/certs/tls.crt
        - --tls-private-key-file=/certs/tls.key
        - --metric_resolution=30s
        - --secure-port=8443
        image: quay.io/openshift/origin-metrics-server:v3.11
        imagePullPolicy: IfNotPresent
        name: metrics-server
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: metrics-server-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/infra: "true"
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metrics-server
      serviceAccountName: metrics-server
      terminationGracePeriodSeconds: 30
      volumes:
      - name: metrics-server-certs
        secret:
          defaultMode: 420
          secretName: metrics-server-certs
status: {}
---
apiVersion: v1
imagePullSecrets:
- name: metrics-server-dockercfg-8knr2
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"kubernetes.io/cluster-service":"true","metrics-server-infra":"support"},"name":"metrics-server","namespace":"openshift-metrics-server"}}
  creationTimestamp: "2022-04-19T14:07:21Z"
  labels:
    kubernetes.io/cluster-service: "true"
    metrics-server-infra: support
  name: metrics-server
  namespace: openshift-metrics-server
  resourceVersion: "3318"
  selfLink: /api/v1/namespaces/openshift-metrics-server/serviceaccounts/metrics-server
  uid: 07fe03dc-bfea-11ec-b9cc-42010a000003
secrets:
- name: metrics-server-dockercfg-8knr2
- name: metrics-server-token-jzbnb
