---
apiVersion: v1
imagePullSecrets:
- name: sdn-dockercfg-bdllv
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"sdn","namespace":"openshift-sdn"}}
  creationTimestamp: "2022-04-19T14:02:04Z"
  name: sdn
  namespace: openshift-sdn
  resourceVersion: "1195"
  selfLink: /api/v1/namespaces/openshift-sdn/serviceaccounts/sdn
  uid: 4a83a0ec-bfe9-11ec-b9cc-42010a000003
secrets:
- name: sdn-dockercfg-bdllv
- name: sdn-token-wzdp5
