---
apiVersion: v1
imagePullSecrets:
- name: deployer-dockercfg-c5csm
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:55Z"
  name: deployer
  namespace: default
  resourceVersion: "913"
  selfLink: /api/v1/namespaces/default/serviceaccounts/deployer
  uid: fdd02668-bfe8-11ec-b9cc-42010a000003
secrets:
- name: deployer-token-h85qh
- name: deployer-dockercfg-c5csm
