---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-04-19T14:03:27Z"
  name: docker-registry
  namespace: default
  resourceVersion: "1945"
  selfLink: /apis/route.openshift.io/v1/namespaces/default/routes/docker-registry
  uid: 7c8d3e94-bfe9-11ec-b9cc-42010a000003
spec:
  rules:
  - host: docker-registry-default.okd.shifter.cloud
    http:
      paths:
      - backend:
          service:
            name: docker-registry
            port: {}
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-19T14:03:25Z"
  labels:
    docker-registry: default
  name: docker-registry
  namespace: default
  resourceVersion: "1977"
  selfLink: /api/v1/namespaces/default/services/docker-registry
  uid: 7b4a86ba-bfe9-11ec-b9cc-42010a000003
spec:
  clusterIP: 172.30.135.232
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    docker-registry: default
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-04-19T14:03:36Z"
  generation: 1
  labels:
    docker-registry: default
  name: docker-registry
  namespace: default
  resourceVersion: "2153"
  selfLink: /apis/apps.openshift.io/v1/namespaces/default/deploymentconfigs/docker-registry
  uid: 81bff1ca-bfe9-11ec-b9cc-42010a000003
spec:
  replicas: 1
  selector:
    matchLabels:
      docker-registry: default
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        docker-registry: default
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_HTTP_NET
          value: tcp
        - name: REGISTRY_HTTP_SECRET
          value: wSOihhCIS94qpm+2UTgeuAOxGOAiiWTrWTwnh9Grip8=
        - name: REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ENFORCEQUOTA
          value: "false"
        - name: OPENSHIFT_DEFAULT_REGISTRY
          value: docker-registry.default.svc:5000
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /etc/secrets/registry.crt
        - name: REGISTRY_OPENSHIFT_SERVER_ADDR
          value: docker-registry.default.svc:5000
        - name: REGISTRY_HTTP_TLS_KEY
          value: /etc/secrets/registry.key
        image: quay.io/openshift/origin-docker-registry:v3.11
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /registry
          name: registry-storage
        - mountPath: /etc/secrets
          name: registry-certificates
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/infra: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: registry
      serviceAccountName: registry
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: registry-storage
      - name: registry-certificates
        secret:
          defaultMode: 420
          secretName: registry-certificates
status: {}
