---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-19T13:59:50Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "8"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: fac3d098-bfe8-11ec-b9cc-42010a000003
spec:
  clusterIP: 172.30.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 8053
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 8053
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
