---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-04-19T14:03:40Z"
  name: registry-console
  namespace: default
  resourceVersion: "2002"
  selfLink: /apis/route.openshift.io/v1/namespaces/default/routes/registry-console
  uid: 843a05d0-bfe9-11ec-b9cc-42010a000003
spec:
  rules:
  - host: registry-console-default.okd.shifter.cloud
    http:
      paths:
      - backend:
          service:
            name: registry-console
            port: {}
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"createdBy":"registry-console-template","name":"registry-console"},"name":"registry-console","namespace":"default"},"spec":{"ports":[{"name":"registry-console","port":9000,"protocol":"TCP","targetPort":9090}],"selector":{"name":"registry-console"},"type":"ClusterIP"}}
  creationTimestamp: "2022-04-19T14:03:42Z"
  labels:
    createdBy: registry-console-template
    name: registry-console
  name: registry-console
  namespace: default
  resourceVersion: "2013"
  selfLink: /api/v1/namespaces/default/services/registry-console
  uid: 84f4fd8b-bfe9-11ec-b9cc-42010a000003
spec:
  clusterIP: 172.30.47.61
  ports:
  - name: registry-console
    port: 9000
    protocol: TCP
    targetPort: 9090
  selector:
    name: registry-console
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"labels":{"createdBy":"registry-console-template","name":"registry-console"},"name":"registry-console","namespace":"default"},"spec":{"replicas":1,"selector":{"name":"registry-console"},"template":{"metadata":{"labels":{"name":"registry-console"}},"spec":{"containers":[{"env":[{"name":"OPENSHIFT_OAUTH_PROVIDER_URL","value":"https://console.okd.shifter.cloud:8443"},{"name":"OPENSHIFT_OAUTH_CLIENT_ID","value":"cockpit-oauth-client"},{"name":"KUBERNETES_INSECURE","value":"false"},{"name":"COCKPIT_KUBE_INSECURE","value":"false"},{"name":"REGISTRY_ONLY","value":"true"},{"name":"REGISTRY_HOST","value":"docker-registry-default.okd.shifter.cloud"}],"image":"registry.access.redhat.com/openshift3/registry-console:v3.11","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/ping","port":9090,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"registry-console","ports":[{"containerPort":9090,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/ping","port":9090,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5}}],"nodeSelector":{"node-role.kubernetes.io/master":"true"}}},"triggers":[{"type":"ConfigChange"}]}}
  creationTimestamp: "2022-04-19T14:03:42Z"
  generation: 1
  labels:
    createdBy: registry-console-template
    name: registry-console
  name: registry-console
  namespace: default
  resourceVersion: "2221"
  selfLink: /apis/apps.openshift.io/v1/namespaces/default/deploymentconfigs/registry-console
  uid: 84f2a28e-bfe9-11ec-b9cc-42010a000003
spec:
  replicas: 1
  selector:
    matchLabels:
      name: registry-console
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: registry-console
    spec:
      containers:
      - env:
        - name: OPENSHIFT_OAUTH_PROVIDER_URL
          value: https://console.okd.shifter.cloud:8443
        - name: OPENSHIFT_OAUTH_CLIENT_ID
          value: cockpit-oauth-client
        - name: KUBERNETES_INSECURE
          value: "false"
        - name: COCKPIT_KUBE_INSECURE
          value: "false"
        - name: REGISTRY_ONLY
          value: "true"
        - name: REGISTRY_HOST
          value: docker-registry-default.okd.shifter.cloud
        image: registry.access.redhat.com/openshift3/registry-console:v3.11
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: registry-console
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
