---
apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-gbltz
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:55Z"
  name: default
  namespace: kube-public
  resourceVersion: "792"
  selfLink: /api/v1/namespaces/kube-public/serviceaccounts/default
  uid: fdade0af-bfe8-11ec-b9cc-42010a000003
secrets:
- name: default-token-9gr6w
- name: default-dockercfg-gbltz
