---
apiVersion: v1
imagePullSecrets:
- name: build-config-change-controller-dockercfg-xvql5
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T13:59:54Z"
  name: build-config-change-controller
  namespace: openshift-infra
  resourceVersion: "849"
  selfLink: /api/v1/namespaces/openshift-infra/serviceaccounts/build-config-change-controller
  uid: fd2e85cb-bfe8-11ec-b9cc-42010a000003
secrets:
- name: build-config-change-controller-token-tgcss
- name: build-config-change-controller-dockercfg-xvql5
