---
apiVersion: v1
imagePullSecrets:
- name: cassandra-dockercfg-28chh
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T14:05:48Z"
  labels:
    metrics-infra: support
  name: cassandra
  namespace: openshift-infra
  resourceVersion: "2778"
  selfLink: /api/v1/namespaces/openshift-infra/serviceaccounts/cassandra
  uid: d01b26ae-bfe9-11ec-b9cc-42010a000003
secrets:
- name: hawkular-cassandra-certs
- name: cassandra-dockercfg-28chh
- name: cassandra-token-c7nnn
