---
apiVersion: v1
imagePullSecrets:
- name: hawkular-dockercfg-dg5wd
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T14:05:47Z"
  labels:
    metrics-infra: support
  name: hawkular
  namespace: openshift-infra
  resourceVersion: "2770"
  selfLink: /api/v1/namespaces/openshift-infra/serviceaccounts/hawkular
  uid: cf926e96-bfe9-11ec-b9cc-42010a000003
secrets:
- name: hawkular-metrics-account
- name: hawkular-metrics-certs
- name: hawkular-token-s7skt
- name: hawkular-dockercfg-dg5wd
