---
apiVersion: v1
imagePullSecrets:
- name: aggregated-logging-elasticsearch-dockercfg-vw57w
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-04-19T14:08:26Z"
  name: aggregated-logging-elasticsearch
  namespace: openshift-logging
  resourceVersion: "3502"
  selfLink: /api/v1/namespaces/openshift-logging/serviceaccounts/aggregated-logging-elasticsearch
  uid: 2e372270-bfea-11ec-b9cc-42010a000003
secrets:
- name: logging-elasticsearch
- name: aggregated-logging-elasticsearch-token-9rzjb
- name: aggregated-logging-elasticsearch-dockercfg-vw57w
